language: python
python:
  - "2.6"
install:
  - lsb_release -a
  - sudo apt-get update && sudo apt-get install linux-headers-generic
  - sudo apt-get install virtualbox ruby1.9.1
  - wget https://dl.bintray.com/mitchellh/vagrant/vagrant_1.6.3_i686.deb
  - sudo dpkg -i vagrant_1.6.3_i686.deb
  - VBoxManage -v
script:
  - which vagrant
  - rvm use system --default
  - vagrant up
  - ls
  - vagrant ssh --command "touch /vagrant/smash_it_with_a_hammer"
  - ls