language: python
python:
  - "2.6"
install:
  - lsb_release -a
  - sudo apt-get update
  - sudo apt-get -y install linux-headers-generic
  - sudo ./virtualbox.sh
  - sudo apt-get install ruby vagrant
  - VBoxManage -v
script:
  - which vagrant
  - rvm use system --default
  - vagrant up
  - ls
  - vagrant ssh --command "touch /vagrant/smash_it_with_a_hammer"
  - ls