language: python
python:
  - "2.6"
install:
  - lsb_release -a
  - sudo apt-get update && sudo apt-get install linux-headers-2.6.32-45-generic
  - sudo apt-get install ruby virtualbox vagrant
  - VBoxManage -v
script:
  - which vagrant
  - vagrant up
  - ls
  - vagrant ssh --command "touch /vagrant/smash_it_with_a_hammer"
  - ls