language: python
python:
  - "2.6"
install:
  - lsb_release -a
  - sudo echo "deb http://download.virtualbox.org/virtualbox/debian precise contrib" | sudo tee -a /etc/apt/sources.list
  - wget http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -y install linux-headers-generic
  - sudo apt-get -y install virtualbox-4.1
  - sudo apt-get install virtualbox ruby vagrant
  - VBoxManage -v
script:
  - which vagrant
  - rvm use system --default
  - vagrant up
  - ls
  - vagrant ssh --command "touch /vagrant/smash_it_with_a_hammer"
  - ls